apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: vllm-monitoring
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    name: web
  selector:
    app: prometheus

